// Command gen-invokes emits exhost/invokes.go: the full matrix of Emscripten
// invoke_<sig> trampolines that a real DuckDB -fexceptions build imports from
// "env". Each trampoline performs the wrapped indirect call through the
// module's function table under the Host's recover-based unwind, so a C++
// throw turns into setThrew + a zero return rather than a Go panic escaping.
//
// Signature encoding (Emscripten): the suffix after invoke_ is one char per
// value type, first char = RETURN, remaining = ARGS. The trampoline's own
// FIRST parameter is always the i32 table index, then the call args.
//
//	i = i32   j = i64   f = float32   d = float64   v = void(return only)
//
// We generate the union that covers any plausible DuckDB build:
//   - return in {v,i,j,f,d}
//   - all-i32 arg runs of length 0..maxI32Args (the dominant family)
//   - arg runs that include up to maxWideArgs non-i32 args (j/f/d), the rest
//     i32, in every position (covers callbacks taking doubles, i64 handles, ...)
//
// The list can also be regenerated to EXACTLY a target wasm's imports by
// passing -names with a comma-separated invoke_ list (e.g. from
// `wasm-objdump -j Import -x duckdb.wasm | grep invoke_`). When -names is empty
// the full matrix below is emitted.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Bounds chosen so the emitted baseline is a finite superset of what an emcc
// C++ build actually imports (dominated by all-i32 and void/i32 returns), not a
// full 5^n cross-product. For an EXACT match to a real DuckDB wasm, pass -names
// with that wasm's invoke_ import list; this baseline is the fallback.
const (
	maxI32Args  = 16 // longest all-i32 arg run to emit
	maxWideArgs = 1  // at most one j/f/d arg in a mixed signature
	maxTotal    = 6  // cap total args for mixed (wide+i32) signatures
)

var goType = map[byte]string{
	'i': "int32",
	'j': "int64",
	'f': "float32",
	'd': "float64",
}

// sigs returns every signature suffix (return char + arg chars) to generate.
func sigs() []string {
	set := map[string]struct{}{}
	rets := []byte{'v', 'i', 'j', 'f', 'd'}

	// Family 1: all-i32 args, length 0..maxI32Args, every return type.
	for _, r := range rets {
		for n := 0; n <= maxI32Args; n++ {
			set[string(r)+strings.Repeat("i", n)] = struct{}{}
		}
	}

	// Family 2: signatures containing 1..maxWideArgs non-i32 args (j/f/d) in any
	// position, padded with i32, total length 1..maxTotal, every return type.
	wide := []byte{'j', 'f', 'd'}
	var build func(prefix []byte, wideLeft int)
	build = func(prefix []byte, wideLeft int) {
		if len(prefix) > maxTotal {
			return
		}
		if len(prefix) >= 1 {
			for _, r := range rets {
				set[string(r)+string(prefix)] = struct{}{}
			}
		}
		if len(prefix) == maxTotal {
			return
		}
		// extend with an i32
		build(append(append([]byte{}, prefix...), 'i'), wideLeft)
		// extend with a wide arg, if budget remains
		if wideLeft > 0 {
			for _, w := range wide {
				build(append(append([]byte{}, prefix...), w), wideLeft-1)
			}
		}
	}
	build(nil, maxWideArgs)

	out := make([]string, 0, len(set))
	for s := range set {
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

// goFnType is the Go function type the table entry is asserted to, e.g.
// "func(int32, float64) int64" for suffix "jid" wait - decode: ret=j, args=id.
func goFnType(sig string) (retGo string, argGo []string) {
	if sig[0] != 'v' {
		retGo = goType[sig[0]]
	}
	for i := 1; i < len(sig); i++ {
		argGo = append(argGo, goType[sig[i]])
	}
	return
}

func main() {
	names := flag.String("names", "", "comma-separated invoke_ names to emit exactly (overrides the full matrix)")
	out := flag.String("o", "", "output Go file (required)")
	flag.Parse()
	if *out == "" {
		fmt.Fprintln(os.Stderr, "-o required")
		os.Exit(2)
	}

	var suffixes []string
	if strings.TrimSpace(*names) != "" {
		seen := map[string]struct{}{}
		for _, n := range strings.Split(*names, ",") {
			n = strings.TrimSpace(n)
			n = strings.TrimPrefix(n, "env.")
			if !strings.HasPrefix(n, "invoke_") {
				continue
			}
			suffixes = append(suffixes, strings.TrimPrefix(n, "invoke_"))
			seen[n] = struct{}{}
		}
		sort.Strings(suffixes)
	} else {
		suffixes = sigs()
	}

	var b strings.Builder
	b.WriteString("// Code generated by gen-invokes. DO NOT EDIT.\n//\n")
	b.WriteString("// invoke_<sig> trampolines for the Emscripten exception ABI. Each performs the\n")
	b.WriteString("// wrapped indirect call at table[index] under Host.trampoline, so a thrown C++\n")
	b.WriteString("// exception is converted to module.setThrew + a zero return.\n\n")
	b.WriteString("package exhost\n\n")

	var counts struct{ f32, f64, i32, i64, void int }
	for _, sig := range suffixes {
		ret, args := goFnType(sig)
		switch sig[0] {
		case 'f':
			counts.f32++
		case 'd':
			counts.f64++
		case 'i':
			counts.i32++
		case 'j':
			counts.i64++
		case 'v':
			counts.void++
		}

		// method params: index then a0..aN
		params := []string{"index int32"}
		callArgs := []string{}
		for i, t := range args {
			params = append(params, fmt.Sprintf("a%d %s", i, t))
			callArgs = append(callArgs, fmt.Sprintf("a%d", i))
		}
		retDecl := ""
		if ret != "" {
			retDecl = " " + ret
		}

		fnTypeParams := make([]string, len(args))
		copy(fnTypeParams, args)
		fnType := "func(" + strings.Join(fnTypeParams, ", ") + ")"
		if ret != "" {
			fnType += " " + ret
		}

		fmt.Fprintf(&b, "func (h *Host) Xinvoke_%s(%s)%s {\n", sig, strings.Join(params, ", "), retDecl)
		if ret != "" {
			fmt.Fprintf(&b, "\tvar ret %s\n", ret)
		}
		b.WriteString("\th.trampoline(func() {\n")
		fmt.Fprintf(&b, "\t\tf := h.table()[index].(%s)\n", fnType)
		if ret != "" {
			fmt.Fprintf(&b, "\t\tret = f(%s)\n", strings.Join(callArgs, ", "))
		} else {
			fmt.Fprintf(&b, "\t\tf(%s)\n", strings.Join(callArgs, ", "))
		}
		b.WriteString("\t})\n")
		if ret != "" {
			b.WriteString("\treturn ret\n")
		}
		b.WriteString("}\n\n")
	}

	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s: %d trampolines (f32-ret=%d f64-ret=%d i32-ret=%d i64-ret=%d void=%d)\n",
		*out, len(suffixes), counts.f32, counts.f64, counts.i32, counts.i64, counts.void)
}
